In [29]:
#importing the file and the required python library for data cleaning
import pandas as pd
df=pd.read_excel(r"C:\Users\mark kevin\Downloads\Data Analyst _ Sample Data _HDM.xlsx")
df.head()

,Call Id,Lead Id,Campaign ID,Advertiser Id,Hid,Call Status,Lead Status,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,To Calling Number,Attempt No,Created At,Updated At,Agent Id,Agent Name
0,26807,410987,930228,1883,40831aceu6850re1ece43deeqf20a6o,no-answer,Not Interested,8,0,9.186570e+11,9.195528e+11,1,2024-04-01 11:35:19,2024-04-01 11:35:27,2728,Mansi Jaiswal
1,26808,410986,930228,1883,3dc489fbg6850pe1ece43deewf20a6v,completed,Not Interested,51,34,9.186570e+11,9.172755e+11,1,2024-04-01 11:35:27,2024-04-01 11:36:19,2728,Mansi Jaiswal
2,26809,410985,930228,1883,92d7bfbag6850se1ece43deevf20a6y,no-answer,Invalid Number,9,0,9.186570e+11,9.194307e+11,1,2024-04-01 11:36:19,2024-04-01 11:36:28,2728,Mansi Jaiswal
3,26810,410984,930228,1883,3a9872eem6850oe1ece43deetf20a6m,completed,Not Interested,45,25,9.186570e+11,9.183493e+11,1,2024-04-01 11:36:29,2024-04-01 11:37:15,2728,Mansi Jaiswal
4,26811,410981,930228,1883,3dde873bx6850je1ece43deehf20a6u,no-answer,Busy,45,0,9.186570e+11,9.170547e+11,1,2024-04-01 11:37:14,2024-04-01 11:38:00,2728,Mansi Jaiswal

In [30]:
# Drop duplicates
df.drop_duplicates(inplace=True)

In [31]:
numerical_columns = ['Agent Duration(seconds)', 'Customer Duration(seconds)', 'Attempt No']

In [32]:
categorical_columns = ['Call Status', 'Lead Status', 'Agent Name', 'Call Status']

In [33]:
# Handle missing values
for column in numerical_columns:
    df[column].fillna(df[column].mean(), inplace=True)

In [34]:
# Handle missing values
for column in categorical_columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

In [35]:
date_columns = ['Created At', 'Updated At']

In [36]:
#Change date in to date format
for column in date_columns:
    df[column] = pd.to_datetime(df[column])

In [37]:
for column in categorical_columns:
    df[column] = df[column].astype('category')

In [38]:
df.head()

,Call Id,Lead Id,Campaign ID,Advertiser Id,Hid,Call Status,Lead Status,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,To Calling Number,Attempt No,Created At,Updated At,Agent Id,Agent Name
0,26807,410987,930228,1883,40831aceu6850re1ece43deeqf20a6o,no-answer,Not Interested,8,0,9.186570e+11,9.195528e+11,1,2024-04-01 11:35:19,2024-04-01 11:35:27,2728,Mansi Jaiswal
1,26808,410986,930228,1883,3dc489fbg6850pe1ece43deewf20a6v,completed,Not Interested,51,34,9.186570e+11,9.172755e+11,1,2024-04-01 11:35:27,2024-04-01 11:36:19,2728,Mansi Jaiswal
2,26809,410985,930228,1883,92d7bfbag6850se1ece43deevf20a6y,no-answer,Invalid Number,9,0,9.186570e+11,9.194307e+11,1,2024-04-01 11:36:19,2024-04-01 11:36:28,2728,Mansi Jaiswal
3,26810,410984,930228,1883,3a9872eem6850oe1ece43deetf20a6m,completed,Not Interested,45,25,9.186570e+11,9.183493e+11,1,2024-04-01 11:36:29,2024-04-01 11:37:15,2728,Mansi Jaiswal
4,26811,410981,930228,1883,3dde873bx6850je1ece43deehf20a6u,no-answer,Busy,45,0,9.186570e+11,9.170547e+11,1,2024-04-01 11:37:14,2024-04-01 11:38:00,2728,Mansi Jaiswal

In [39]:
df.isnull().sum()

Call Id                         0
Lead Id                         0
Campaign ID                     0
Advertiser Id                   0
Hid                             0
Call Status                     0
Lead Status                     0
Agent Duration(seconds)         0
Customer Duration(seconds)      0
From Calling Number           123
To Calling Number               6
Attempt No                      0
Created At                      0
Updated At                      0
Agent Id                        0
Agent Name                      0
dtype: int64

In [40]:
#Remove null values
df['From Calling Number'].fillna('Unknown', inplace=True)

In [41]:
df.isnull().sum()

Call Id                       0
Lead Id                       0
Campaign ID                   0
Advertiser Id                 0
Hid                           0
Call Status                   0
Lead Status                   0
Agent Duration(seconds)       0
Customer Duration(seconds)    0
From Calling Number           0
To Calling Number             6
Attempt No                    0
Created At                    0
Updated At                    0
Agent Id                      0
Agent Name                    0
dtype: int64

In [44]:
#Save the cleaned fine
cleaned_file_path = 'cleaned_data.xlsx'
df.to_excel(cleaned_file_path, index=False)
print(f"\nCleaned data saved to {cleaned_file_path}")

Cleaned data saved to cleaned_data.xlsx